apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carts
  links:
    - url: https://microservices-demo.github.io/api/index?url=https://raw.githubusercontent.com/microservices-demo/carts/master/api-spec/cart.json
      title: Carts introduction
      icon: dashboard
  annotations:
    jira/project-key: CARTS
    github.com/project-slug: 'seal-demo/carts'
    backstage.io/kubernetes-id: carts
    fossa.io/project-name: carts
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: socks-shop
  dependsOn:
    - component:default/catalogue
  providesApis:
    - carts-api
  consumesApis:
    - catalogue-api
  
