apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carts
  annotations:
    jira/project-key: CARTS
    github.com/project-slug: 'seal-demo/carts'
    backstage.io/kubernetes-id: carts
    fossa.io/project-name: carts
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: socks-shop
  providesApis:
    - carts-api
